name: Build Website

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repo
        uses: actions/checkout@v4

      - name: Build NextJs Page
        run: |
          npm i
          npm task build

      - name: Build Rust Backend
        run: cargo build --release

      - name: Pack Output
        run: mkdir output | mv .next output | mv target/release/backend | 7z a -tzip output.zip output

      - name: Output
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: output.zip
