name: Build Website

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest

    steps:
      - name: Setup Repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - uses: actions/cache@v4
        with:
          path: |
            ~/.deno
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Deno Build
        run: |
          deno i
          deno task build

      - uses: actions/upload-artifact@v4
        with:
          name: NextJsBuild
          path: .next/
          include-hidden-files: true
